### ISSUE TITLE
Młody to miało być JavaScript zadanko a nie jakieś abstrakcje

### ISSUE THREAD

**Issue by karolkruszynski** [KacperBojarczuk/kurs#1]

**Comment by KacperBojarczuk** [comment]
![hmmm](https://user-images.githubusercontent.com/130044654/230343370-0d34caa8-3c8b-4073-b9e7-8ae658d2ce2e.gif)

**Comment by karolkruszynski** [comment]
https://user-images.githubusercontent.com/90861840/230344092-61cca85d-e56a-4601-aa7d-0511b2d24535.mp4
